<?php
return array (
  'app' => 'Admin',
  'model' => 'Service',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '业务管理',
  'icon' => '',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Serve',
      'action' => 'Index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '服务管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Order',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '订单管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Ad',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '广告管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Addus',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '加入我们',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Reward',
      'action' => 'Index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '打赏查询',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);